from __future__ import annotations

import html as _html
import io

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from ..utils.formatters import format_ci, format_effect, format_effect_pct, format_p_value


def generate_pdf_report(
    dates: list[str],
    observed: list[float],
    counterfactual: list[float],
    intervention_idx: int,
    effect: float,
    effect_pct: float,
    ci_lower: float,
    ci_upper: float,
    p_value: float,
    significant: bool,
    direction: str,
    metric_name: str,
    method: str,
) -> bytes:
    safe_metric = _html.escape(str(metric_name))
    fig, axes = plt.subplots(2, 1, figsize=(10, 7), gridspec_kw={"height_ratios": [3, 1]})

    ax = axes[0]
    x = range(len(dates))

    ax.plot(x, observed, color="#1e293b", linewidth=1.5, label="Observed")
    ax.plot(x[:intervention_idx], counterfactual[:intervention_idx],
            color="#6366f1", linewidth=1, linestyle="--", label="Fitted (pre)")
    ax.plot(x[intervention_idx:], counterfactual[intervention_idx:],
            color="#ef4444", linewidth=1.5, linestyle="--", label="Counterfactual")

    ax.axvline(x=intervention_idx, color="#f59e0b", linestyle=":", linewidth=1.5, label="Intervention")

    ax.set_title("Causal Impact Analysis", fontsize=14, fontweight="bold")
    ax.set_ylabel(metric_name)
    ax.legend(loc="upper left", fontsize=8)
    ax.set_xticks(x[::max(1, len(x) // 10)])
    ax.set_xticklabels([dates[i] for i in x[::max(1, len(x) // 10)]], rotation=45, fontsize=8)

    ax2 = axes[1]
    effects = np.array(observed) - np.array(counterfactual)
    colors = ["#22c55e" if e > 0 else "#ef4444" for e in effects]
    ax2.bar(x, effects, color=colors, alpha=0.6, width=1.0)
    ax2.axhline(y=0, color="gray", linewidth=0.5)
    ax2.set_ylabel("Effect")
    ax2.set_xlabel("Date")
    ax2.set_xticks(x[::max(1, len(x) // 10)])
    ax2.set_xticklabels([dates[i] for i in x[::max(1, len(x) // 10)]], rotation=45, fontsize=8)

    plt.tight_layout()

    img_buffer = io.BytesIO()
    fig.savefig(img_buffer, format="png", dpi=150, bbox_inches="tight")
    plt.close(fig)
    img_buffer.seek(0)

    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer

    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("CausalLens — Causal Impact Report", styles["Title"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"<b>Metric:</b> {safe_metric}", styles["Normal"]))
    story.append(Paragraph(f"<b>Method:</b> {method.upper()}", styles["Normal"]))
    story.append(Paragraph(f"<b>Intervention:</b> Date index {intervention_idx} ({dates[intervention_idx]})", styles["Normal"]))
    story.append(Spacer(1, 12))

    if significant:
        color = "green" if direction == "increase" else "red"
        story.append(Paragraph(
            f'<font color="{color}"><b>Result: Statistically Significant</b></font>',
            styles["Heading2"],
        ))
    else:
        story.append(Paragraph(
            '<font color="orange"><b>Result: Not Statistically Significant</b></font>',
            styles["Heading2"],
        ))

    story.append(Paragraph(f"<b>Effect:</b> {format_effect(effect)} ({format_effect_pct(effect_pct)})", styles["Normal"]))
    story.append(Paragraph(f"<b>95% CI:</b> {format_ci(ci_lower, ci_upper)}", styles["Normal"]))
    story.append(Paragraph(f"<b>p-value:</b> {format_p_value(p_value)}", styles["Normal"]))
    story.append(Spacer(1, 12))

    chart_img = Image(img_buffer, width=6 * inch, height=4 * inch)
    story.append(chart_img)
    story.append(Spacer(1, 12))

    if significant:
        if direction == "increase":
            story.append(Paragraph(
                f"The intervention caused a {format_effect_pct(abs(effect_pct))} increase in {safe_metric}. "
                f"This effect is statistically significant (p={format_p_value(p_value)}).",
                styles["Normal"],
            ))
        else:
            story.append(Paragraph(
                f"The intervention caused a {format_effect_pct(abs(effect_pct))} decrease in {safe_metric}. "
                f"This effect is statistically significant (p={format_p_value(p_value)}).",
                styles["Normal"],
            ))
    else:
        story.append(Paragraph(
            f"The intervention did not produce a statistically significant effect on {safe_metric} "
            f"(p={format_p_value(p_value)}). The observed change may be due to random variation.",
            styles["Normal"],
        ))

    story.append(Spacer(1, 24))
    story.append(Paragraph(
        "Generated by CausalLens — Causal Impact Calculator",
        styles["Normal"],
    ))

    doc.build(story)
    return pdf_buffer.getvalue()
